-- supabase/migrations/41_fix_usuario_identity.sql
-- Cambiar la configuración de usu_id para permitir inserts manuales cuando sea necesario
-- Esto es necesario para sincronizar con los IDs de Supabase Auth

BEGIN;

-- Cambiar la columna usu_id de GENERATED ALWAYS AS IDENTITY a GENERATED BY DEFAULT AS IDENTITY
-- Esto permite inserts manuales pero mantiene la auto-generación cuando no se especifica
ALTER TABLE public.usuario
ALTER COLUMN usu_id SET GENERATED BY DEFAULT;

-- Agregar comentario explicativo
COMMENT ON COLUMN public.usuario.usu_id IS 'ID del usuario. Puede ser generado automáticamente o provenir de Supabase Auth';

COMMIT;
